# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_v_0.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Connect.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.Connect.setObjectName("Connect")
        self.Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect.setGeometry(QtCore.QRect(20, 80, 93, 28))
        self.Disconnect.setObjectName("Disconnect")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 231, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Connect.clicked.connect(lambda: self.clicked("Connecting..."))
        # self.Connect.clicked.connect(lambda: self.establishConnection())
        self.Disconnect.clicked.connect(lambda: self.clicked("Disconnecting..."))
        # self.Disconnect.clicked.connect(lambda: self.disconnectConnection())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Connect.setText(_translate("MainWindow", "Connect"))
        self.Disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.label.setText(_translate("MainWindow", "Press \"Connect\" to establis connection"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
    
    def clicked(self, text):
        self.label.setText(text)
        self.label.adjustSize()

    # def establishConnection(self):
    #     TXport = "COM3"
    #     TXbaud = 115200 
    #     RXport = "COM4"
    #     RXbaud = 921600
    #     sertx = serial.Serial(TXport,TXbaud)
    #     serrx = serial.Serial(RXport,RXbaud)

    # def disconnectConnection(self):
    #     sertx.close()
    #     serrx.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
